version: "3"

services:
  gather-turtles:
    build:
      context: .
      dockerfile: Dockerfile-go
    container_name: gather-turtles
    restart: always
    networks:
      - backend
    depends_on:
      - timescale
    environment:
      - DB_USER=go
      - DB_NAME=trtl
      - DB_PASSWORD=98765
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_SSLMODE=disable

  timescale:
    build:
      context: .
      dockerfile: Dockerfile-timescale-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - GO_PASSWORD=98765
      - WEB_PASSWORD=98765
    container_name: timescale
    volumes:
      #- timescale:/var/lib/postgresql/data
      - /home/andrewnk/timescaleBackup:/var/lib/postgresql/data
      #- /home/andrewnk/timescaleBackup:/backups
    networks:
      - backend

  # turtlecoind:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-turtlecoind
  #   restart: always
  #   environment:
  #     - TURTLECOIN_PROGRAM=TurtleCoind
  #     - TURTLECOINSERVICE_PASSWORD=98765
  #     - WEB_PASSWORD=98765
  #   container_name: turtlecoind
  #   networks:
  #     - backend

  # turtlecoin-cache-db:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-turtlecoin-cache-db
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - TURTLECOINSERVICE_PASSWORD=98765
  #     - WEB_PASSWORD=98765
  #   container_name: turtlecoin-cache-db
  #   volumes:
  #     - turtlecoin-cache-db:/var/lib/postgresql/data
  #   networks:
  #     - backend

  # turtlecoin-cache-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-turtlecoin-service
  #   restart: always
  #   environment:
  #     - DB_USER=turtlecoinservice
  #     - DB_PASSWORD=98765
  #     - DB_PORT=5432
  #     - DB_HOST=turtlecoin-cache-db
  #     - DB_NAME=turtlecoincache
  #     - TURTLECOIN_PORT=11898
  #     - TURTLECOIN_HOST=turtlecoind
  #   container_name: turtlecoin-cache-service
  #   depends_on: turtlecoin-cache-db
  #   networks:
  #     - backend

  web-backend:
    build:
      context: .
      dockerfile: Dockerfile-web-backend
    restart: always
    container_name: web-backend
    environment:
      - DB_USER=web
      - DB_PASSWORD=98765
      - DB_PORT=5432
      - DB_HOST=timescale
      - DB_NAME=trtl
    depends_on:
      - timescale
      - gather-turtles
      # - turtlecoin-cache-db
    networks:
      - backend
      - frontend

  web-frontend:
    build:
      context: .
      dockerfile: Dockerfile-web-frontend
    restart: always
    container_name: web-frontend
    networks:
      - frontend
    depends_on:
      - timescale
      - gather-turtles
      # - turtlecoin-cache-db
      - web-backend
    ports:
      - 80:3000

  web-cache:
    image: redis:alpine
    container_name: web-cache
    depends_on:
      - web-backend
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16

  frontend:
    driver: bridge
    ipam:
      driver: default

# volumes:
#   timescale: