version: "3"

services:
  gather-turtles:
    build:
      context: .
      dockerfile: Dockerfile-go
    container_name: gather-turtles
    restart: always
    networks:
      - backend
    depends_on:
      - timescale
    environment:
      - DB_USER=go
      - DB_NAME=trtl
      - DB_PASSWORD=98765
      - DB_HOST=timescale
      - DB_PORT=5432
      - DB_SSLMODE=disable

  timescale:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - GO_PASSWORD=98765
      - WEB_PASSWORD=98765
    container_name: timescale
    volumes:
      - timescale:/var/lib/postgresql/data
    networks:
      - backend

  web-backend:
    build:
      context: .
      dockerfile: Dockerfile-web-backend
    restart: always
    container_name: web-backend
    environment:
      - DB_USER=web
      - DB_PASSWORD=98765
      - DB_PORT=5432
      - DB_HOST=timescale
      - DB_NAME=trtl
    depends_on:
      - timescale
      - gather-turtles
    networks:
      - backend
      - frontend

  web-frontend:
    build:
      context: .
      dockerfile: Dockerfile-web-frontend
    restart: always
    container_name: web-frontend
    networks:
      - frontend
    depends_on:
      - timescale
      - gather-turtles
      - web-backend
    ports:
      - 80:3000

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16

  frontend:
    driver: bridge
    ipam:
      driver: default

volumes:
  timescale:
