version: "3"

services:
  gather-turtles:
    volumes:
      - ./go:/go
    tty: true

  web-backend:
    volumes:
      - ./web/backend:/home/node
    tty: true

  web-frontend:
    volumes:
      - ./web/frontend:/home/node
    tty: true
